# Generated by Django 4.2.5 on 2023-11-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="img",
            field=models.TextField(default=200),
            preserve_default=False,
        ),
    ]
